-- MySQL Script generated by MySQL Workbench
-- MySQL Script generated by MySQL Workbench
-- Fri Dec 18 15:13:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizza` DEFAULT CHARACTER SET utf8 ;
USE `pizza` ;

-- -----------------------------------------------------
-- Table `pizza`.`CUSTOMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`CUSTOMER` ;

CREATE TABLE IF NOT EXISTS `pizza`.`CUSTOMER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(14) NOT NULL,
  `address` VARCHAR(100) NULL,
  `point` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`MENU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`MENU` ;

CREATE TABLE IF NOT EXISTS `pizza`.`MENU` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `discountRate` INT NOT NULL DEFAULT 0,
  `orderCount` INT NOT NULL DEFAULT 0,
  `description` VARCHAR(20000) NULL,
  `rating` INT NOT NULL DEFAULT 0,
  `category` VARCHAR(45) NOT NULL CHECK (`category` IN ('standard', 'premium')),
  `review` VARCHAR(1000) NULL,
  `storeId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`CART`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`CART` ;

CREATE TABLE IF NOT EXISTS `pizza`.`CART` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `menuId` INT NOT NULL,
  `price` INT NOT NULL,
  `ea` INT NOT NULL DEFAULT 1,
  `curtomerId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `curtomerId_UNIQUE` (`curtomerId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`ORDERDETAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`ORDERDETAIL` ;

CREATE TABLE IF NOT EXISTS `pizza`.`ORDERDETAIL` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orderId` INT NOT NULL,
  `menuId` INT NOT NULL,
  `ea` INT NOT NULL DEFAULT 1,
  `price` INT NOT NULL,
  `discount` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`CUSTOMERCENTER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`CUSTOMERCENTER` ;

CREATE TABLE IF NOT EXISTS `pizza`.`CUSTOMERCENTER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customerId` INT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `body` VARCHAR(1000) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT now(),
  `status` VARCHAR(45) NOT NULL, CHECK ( `status` IN ('답변대기', '답변완료')),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `customerId_UNIQUE` (`customerId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`Comments` ;

CREATE TABLE IF NOT EXISTS `pizza`.`Comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inquiryId` INT NOT NULL,
  `customerId` INT NOT NULL,
  `comments` VARCHAR(1000) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`STORE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`STORE` ;

CREATE TABLE IF NOT EXISTS `pizza`.`STORE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `loc` VARCHAR(200) NOT NULL,
  `number` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  UNIQUE INDEX `loc_UNIQUE` (`loc` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`ORDER` ;

CREATE TABLE IF NOT EXISTS `pizza`.`ORDER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customerId` INT NOT NULL,
  `storeId` INT NOT NULL,
  `orderDate` DATETIME NOT NULL DEFAULT now(),
  `totalPrice` INT NOT NULL DEFAULT 0,
  `detination` VARCHAR(200) NOT NULL,
  `status` VARCHAR(45) NOT NULL CHECK (`status` IN ('주문완료','결제완료')),
  `hereOrTogo` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `customerId_UNIQUE` (`customerId` ASC) VISIBLE,
  UNIQUE INDEX `storeId_UNIQUE` (`storeId` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
