-- MySQL Script generated by MySQL Workbench
-- MySQL Script generated by MySQL Workbench
-- Fri Dec 18 15:13:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizza` DEFAULT CHARACTER SET utf8 ;
USE `pizza` ;

-- -----------------------------------------------------
-- Table `pizza`.`CUSTOMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`CUSTOMER` ;

CREATE TABLE IF NOT EXISTS `pizza`.`CUSTOMER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(14) NOT NULL,
  `address` VARCHAR(100) NULL,
  `point` INT NOT NULL DEFAULT 0,
  `ismanager` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`MENU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`MENU` ;

CREATE TABLE IF NOT EXISTS `pizza`.`MENU` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `discountRate` INT NOT NULL DEFAULT 0,
  `orderCount` INT NOT NULL DEFAULT 0,
  `description` VARCHAR(20000) NULL,
  `rating` INT NOT NULL DEFAULT 0,
  `category` VARCHAR(45) NOT NULL CHECK (`category` IN ('classic', 'premium')),
  `reviewId` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;

INSERT INTO menu (name, price, category)
VALUES ('Combination', 15900, 'classic');
INSERT INTO menu (name, price, category)
VALUES ('Bulgogi Pizza', 16900, 'classic');
INSERT INTO menu (name, price, category)
VALUES ('Pepperoni Pizza', 15900, 'classic');
INSERT INTO menu (name, price, category)
VALUES ('Brown Pepper Pizza', 16900, 'classic');
INSERT INTO menu (name, price, category)
VALUES ('Margarita Pizza', 17400, 'premium');
INSERT INTO menu (name, price, category)
VALUES ('Barbecue Pizza', 18900, 'premium');
INSERT INTO menu (name, price, category)
VALUES ('Bacon Cheese Pizza', 18900, 'premium');
INSERT INTO menu (name, price, category)
VALUES ('Tomato Basil Pizza', 17400, 'premium');

SELECT * FROM menu;

-- -----------------------------------------------------
-- Table `mydb`.`REVIEW`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`REVIEW` ;

CREATE TABLE IF NOT EXISTS `pizza`.`REVIEW` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `menuId` INT NOT NULL,
  `review` VARCHAR(1000) NOT NULL,
  `customerId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pizza`.`CART`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`CART` ;

CREATE TABLE IF NOT EXISTS `pizza`.`CART` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `menuId` INT NOT NULL UNIQUE,
  `ea` INT NOT NULL DEFAULT 1,
  `customerId` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`ORDERDETAIL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`ORDERDETAIL` ;

CREATE TABLE IF NOT EXISTS `pizza`.`ORDERDETAIL` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `orderId` INT NOT NULL,
  `cartId` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`CUSTOMERCENTER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`CUSTOMERCENTER` ;

CREATE TABLE IF NOT EXISTS `pizza`.`CUSTOMERCENTER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) CHECK (`category` IN ('customer', 'order', 'etc')),
  `customerId` VARCHAR(45) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `content` VARCHAR(1000) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT now(),
  `status` TINYINT DEFAULT 0 NOT NULL, CHECK ( `status` IN (0, 1)),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`COMMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`COMMENT` ;

CREATE TABLE IF NOT EXISTS `pizza`.`COMMENT` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inquiryId` INT NOT NULL,
  `customerId` VARCHAR(45) NOT NULL,
  `comments` VARCHAR(1000) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`STORE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`STORE` ;

CREATE TABLE IF NOT EXISTS `pizza`.`STORE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `loc` VARCHAR(200) NOT NULL,
  `number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  UNIQUE INDEX `loc_UNIQUE` (`loc` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;

INSERT INTO store (name, loc, number)
VALUES ('이대점', '서울특별시 서대문구 123-1', '070-1234-2424');
INSERT INTO store (name, loc, number)
VALUES ('홍대점', '서울특별시 마포구 234-2', '070-5678-2424');
INSERT INTO store (name, loc, number)
VALUES ('검암점', '인천광역시 서구 345-3', '070-0987-2424');

SELECT * FROM store;

-- -----------------------------------------------------
-- Table `pizza`.`ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizza`.`ORDER` ;

CREATE TABLE IF NOT EXISTS `pizza`.`ORDER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customerId` INT NOT NULL,
  `storeId` INT NOT NULL,
  `orderDate` DATETIME NOT NULL DEFAULT now(),
  `totalPrice` INT NOT NULL DEFAULT 0,
  `totalDiscount` INT NOT NULL DEFAULT 0,
  `detination` VARCHAR(200),
  `status` VARCHAR(45) NOT NULL CHECK (`status` IN ('주문완료','결제완료')),
  `togoOrWrap` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `customerId_UNIQUE` (`customerId` ASC) VISIBLE,
  UNIQUE INDEX `storeId_UNIQUE` (`storeId` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- VIEW 생성
DROP VIEW `cartDetail`;
CREATE VIEW `cartDetail` AS
SELECT cart.id,  menu.name menuName, cart.menuId, cart.ea, cart.customerId
FROM `pizza`.`cart` AS cart, `pizza`.`menu` AS menu
WHERE cart.menuId = menu.id;

