-- MySQL Script generated by MySQL Workbench
-- MySQL Script generated by MySQL Workbench
-- Fri Dec 18 15:13:12 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizza
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `pizza` DEFAULT CHARACTER SET utf8 ;
-- USE `pizza` ;

-- -----------------------------------------------------
-- Table `pizza`.`CUSTOMER`
-- -----------------------------------------------------
DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER (
  id NUMBER GENERATED AS IDENTITY,
  userId VARCHAR2(45) NOT NULL UNIQUE,
  name VARCHAR2(45) NOT NULL,
  password VARCHAR2(45) NOT NULL,
  phone VARCHAR2(14) NOT NULL,
  address VARCHAR2(100),
  point NUMBER DEFAULT 0 NOT NULL,
  ismanager NUMBER(1) DEFAULT 0 NOT NULL,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table `pizza`.`MENU`
-- -----------------------------------------------------
DROP TABLE MENU;

CREATE TABLE MENU (
  id NUMBER GENERATED AS IDENTITY,
  name VARCHAR2(45) NOT NULL UNIQUE,
  price NUMBER NOT NULL,
  discountRate NUMBER DEFAULT 0 NOT NULL,
  orderCount NUMBER DEFAULT 0 NOT NULL,
  description VARCHAR2(20000) NULL,
  rating NUMBER DEFAULT 0 NOT NULL,
  category VARCHAR2(45) NOT NULL CHECK (category IN ('classic', 'premium')),
  reviewId NUMBER,
  PRIMARY KEY (id));

INSERT INTO menu (name, price, category)
VALUES ('Combination', 15900, 'classic');
INSERT INTO menu (name, price, category)
VALUES ('Bulgogi Pizza', 16900, 'classic');
INSERT INTO menu (name, price, category)
VALUES ('Pepperoni Pizza', 15900, 'classic');
INSERT INTO menu (name, price, category)
VALUES ('Brown Pepper Pizza', 16900, 'classic');
INSERT INTO menu (name, price, category)
VALUES ('Margarita Pizza', 17400, 'premium');
INSERT INTO menu (name, price, category)
VALUES ('Barbecue Pizza', 18900, 'premium');
INSERT INTO menu (name, price, category)
VALUES ('Bacon Cheese Pizza', 18900, 'premium');
INSERT INTO menu (name, price, category)
VALUES ('Tomato Basil Pizza', 17400, 'premium');

SELECT * FROM menu;

-- -----------------------------------------------------
-- Table `pizza`.`CART`
-- -----------------------------------------------------
DROP TABLE CART;

CREATE TABLE CART (
  id NUMBER GENERATED AS IDENTITY,
  menuId NUMBER NOT NULL,
  price NUMBER NOT NULL,
  ea NUMBER DEFAULT 1 NOT NULL,
  curtomerId NUMBER NOT NULL UNIQUE,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table `pizza`.`ORDERDETAIL`
-- -----------------------------------------------------
DROP TABLE ORDERDETAIL;

CREATE TABLE ORDERDETAIL (
  id NUMBER GENERATED AS IDENTITY,
  orderId NUMBER NOT NULL,
  menuId NUMBER NOT NULL,
  ea NUMBER DEFAULT 1 NOT NULL,
  price NUMBER NOT NULL,
  discount NUMBER DEFAULT 0 NOT NULL,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table `pizza`.`CUSTOMERCENTER`
-- -----------------------------------------------------
DROP TABLE CUSTOMERCENTER;

CREATE TABLE CUSTOMERCENTER (
  id NUMBER GENERATED AS IDENTITY,
  category VARCHAR2(45) CHECK (category IN ('customer', 'order', 'etc')),
  customerId VARCHAR2(45) NOT NULL,
  title VARCHAR2(200) NOT NULL,
  content VARCHAR2(1000) NOT NULL,
  date0 DATE DEFAULT sysdate NOT NULL,
  status NUMBER(1) DEFAULT 0 NOT NULL, CHECK ( status IN (0, 1)),
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table `pizza`.`COMMENT`
-- -----------------------------------------------------
DROP TABLE COMMENT0;

CREATE TABLE COMMENT0 (
  id NUMBER GENERATED AS IDENTITY,
  inquiryId NUMBER NOT NULL,
  customerId VARCHAR2(45) NOT NULL,
  comments VARCHAR2(1000) NOT NULL,
  date0 DATE DEFAULT sysdate NOT NULL,
  PRIMARY KEY (id));


-- -----------------------------------------------------
-- Table `pizza`.`STORE`
-- -----------------------------------------------------
DROP TABLE STORE;

CREATE TABLE STORE (
  id NUMBER GENERATED AS IDENTITY,
  name VARCHAR2(45) NOT NULL UNIQUE,
  loc VARCHAR2(200) NOT NULL UNIQUE,
  number0 VARCHAR2(45) NULL UNIQUE,
  PRIMARY KEY (id));

INSERT INTO store (name, loc, number0)
VALUES ('이대점', '서울특별시 서대문구 123-1', '070-1234-2424');
INSERT INTO store (name, loc, number0)
VALUES ('홍대점', '서울특별시 마포구 234-2', '070-5678-2424');
INSERT INTO store (name, loc, number0)
VALUES ('검암점', '인천광역시 서구 345-3', '070-0987-2424');

SELECT * FROM store;

-- -----------------------------------------------------
-- Table `pizza`.`ORDER`
-- -----------------------------------------------------
DROP TABLE ORDER0;

CREATE TABLE ORDER0 (
  id NUMBER GENERATED AS IDENTITY,
  customerId INT NOT NULL UNIQUE,
  storeId INT NOT NULL UNIQUE,
  orderDate DATE DEFAULT sysdate NOT NULL,
  totalPrice INT DEFAULT 0 NOT NULL,
  detination VARCHAR(200) NOT NULL,
  status VARCHAR(45) NOT NULL CHECK (status IN ('주문완료','결제완료')),
  hereOrTogo NUMBER(1) NOT NULL,
  PRIMARY KEY (id));


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
